[build]
prebuild = ["echo 'Pre-build step'"]
build = ["echo 'Main build step'"]
postbuild = ["echo 'Post-build step'"]
exclude = [
    ".git",
    "target",
    "*.log",
    ".vscode",
    ".idea",
    "node_modules",
    "__pycache__",
]

[package]
compression = "default"
zip_name = "default"

[scripts]
lint = "echo 'Linting code...'"
test = "echo 'Running tests...'"



